version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: starman
    main: ./cmd/starman/
    binary: starman
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/morehao/starman/internal/version.ver={{.Version}}
      - -X github.com/morehao/starman/internal/version.commit={{.Commit}}
      - -X github.com/morehao/starman/internal/version.date={{.Date}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - Merge pull request
      - Merge branch
